environments: 
    development:
        storage: abfss://datalake@datalake.dfs.core.windows.net
        location: "{{ storage }}/databricks/{{ database_home }}/{{ database_folder_name }}/{{ table_name }}"

    production:
        storage: abfss://lalalala
        location: "{{ storage }}/databricks/{{ database_home }}/{{ database_folder_name }}/{{ table_name }}"

projects : 
    TestDB: 
        TestDBSql1 :
            database_folder_name: testdb
            database_home: delta
            format: delta
            table_type: UNMANAGED
        TestDBSql2:
            database_folder_name: testdb
            database_home: delta
            format: delta
            table_type: UNMANAGED

